### ISSUE TITLE
[Bug] Icons not showing in search

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/QuickSearch-for-Playnite#1]
From version 0.5 to 1.1.0 icons don't show

![image](https://user-images.githubusercontent.com/1389286/119720108-306b2280-be2f-11eb-87c2-a049a767ea82.png)

![image](https://user-images.githubusercontent.com/1389286/119720787-07975d00-be30-11eb-9f32-0999b12ac5fc.png)

![image](https://user-images.githubusercontent.com/1389286/119720799-0d8d3e00-be30-11eb-8ba8-7b7c3b4f7e14.png)

Version 0.4.2 and prior show icons fine.

**Comment by felixkmh** [comment]
Thanks for the report. Fixed in b49d7f01f5d8f5bc754a5697dc9a71a6ccd0ecca

**Comment by felixkmh** [comment]
released a hotfix with version 1.1.1

**Comment by darklinkpower** [comment]
Thanks. By the way, I see you are combining the paths as long as the Icon property is not null. It can be an issue with games that have the asset set via Url. What I've done to detect if they are an url is use regex to see if they match `^http`

I also recommend using this method to get the file path instead of combining https://playnite.link/docs/api/Playnite.SDK.IGameDatabaseAPI.html#Playnite_SDK_IGameDatabaseAPI_GetFullFilePath_System_String_

Example: `PlayniteApi.Database.GetFullFilePath(game.Icon)`
