### ISSUE TITLE
[Feature Request] Allow QuickSearch to be launched outside of playnite

### ISSUE THREAD

**Issue by trillex** [felixkmh/QuickSearch-for-Playnite#23]
I am not entirely sure that this is even possible, but I would love it if it the QuickSearch prompt could popup if pressing certain hotkeys without having Playnite focused. 

Akin to pressing windows button and start typing to search for software, it could quickly pop up, allow you to find the game you want and launch it.

**Comment by felixkmh** [comment]
This should already be possible using the global hotkey in the plugin settings. But it is disabled by default, so you will need to enable it first.

**Comment by trillex** [comment]
You are right, in my excitement of my idea, I must have missed that over the previous version I had prior to updating to Playnite 9. 

I'll close the ticket.
