### ISSUE TITLE
Don't show global hotkey window in taskbar

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/QuickSearch-for-Playnite#27]
Currently it shows in the taskbar
![image](https://user-images.githubusercontent.com/1389286/139280182-397ff282-8cd4-435f-88f1-b5d343f0d81e.png)

The window `ShowInTaskbar` property could be set to false to change this

**Comment by felixkmh** [comment]
done via 667996774c6045716e327d59023714a0d85438ff
