### ISSUE TITLE
Playnite (9.6) search behaviour isn't being overwritten

### ISSUE THREAD

**Issue by ClearStrelok** [felixkmh/QuickSearch-for-Playnite#28]
The extension has been working perfectly for weeks so I'm kind of puzzled as to what is suddenly causing the issue, but here goes : currently, the default search behaviour (non global Ctrl+F) has stopped working completely, including when trying to change the  shortcut,  with CTRL+F now reverting to Playnite's default search bar. The global shortcut does work, but it too seems to be only partially functionnal (transparency is gone, for example)

This is happening with version 2.11.5 of the extension regardless of themes or other installed extensions. I've tried reinstalling the extension to no avail, but the parameters seem to be restored even when deleting the corresponding folder, so I'll have to verify that the issue isn't on my end with a portable installation.

**Comment by felixkmh** [comment]
This is why: 
![grafik](https://user-images.githubusercontent.com/24227002/139594137-9c09a209-1427-41d4-b394-36bfc15a6000.png)
For some reason the listener window is returned as the current main window, to which the shortcut is then registered.

**Comment by felixkmh** [comment]
fixed via 9109c112316c09402c4614a61c0fe60b06a5c57f
