### ISSUE TITLE
[Feature Request] Support searching for tags

### ISSUE THREAD

**Issue by antcodd** [felixkmh/QuickSearch-for-Playnite#39]
Currently QuickSearch doesn't seem to support searching on tags as a filter (or it isn't working for me).

When using the Steam Tags Importer and/or PCGamingWiki metadata source you can end up with a very large number of tags that Playnite doesn't have a way to quick filter on (I have over 500). QuickSearch seems like the perfect solution for this.

**Comment by felixkmh** [comment]
done via 8194f2c284ebe070e4531b083b4415ffb8f077af
