### ISSUE TITLE
[Feature Request] Option to use cover art in place of icon

### ISSUE THREAD

**Issue by savvasdalkitsis** [felixkmh/QuickSearch-for-Playnite#4]
Many games are missing icons and are harder to grok visually when searching.

It would be amazing if we had an option to either use cover arts in place of missing icons or to optionally only use cover arts instead of icons in the pop up window

**Comment by felixkmh** [comment]
done via e770c9d1f0e8250eb71aa2f09853a7c096b41db1.
Now, if there is no icon, the cover art is used the icon if it is available. And there is a new option to always prefer the cover art if it exists.
