### ISSUE TITLE
Possibility to turn off adding tags automatically

### ISSUE THREAD

**Issue by XenorPLxx** [felixkmh/QuickSearch-for-Playnite#40]
Hi!
Could you add an option to turn off adding tags automatically? Removing the tag doesn't work - it always comes back.
![image](https://user-images.githubusercontent.com/6712823/159904590-8253562c-d0ff-4665-b52a-52f488db7a1d.png)

**Comment by terrehbyte** [comment]
This was added in [QuickSearch v2.17.0](https://github.com/felixkmh/QuickSearch-for-Playnite/releases/tag/v2.17.0), so hopefully you're all set now:

![image](https://user-images.githubusercontent.com/4968773/168686057-1e643f19-0cf3-4db2-8fd8-7d2b53d971b5.png)

**Comment by XenorPLxx** [comment]
Yup, it works, thanks for letting me know :).
