### ISSUE TITLE
IsThereAnyDeal error prevents other search results being shown

### ISSUE THREAD

**Issue by Jeshibu** [felixkmh/QuickSearch-for-Playnite#54]
```
26-05 15:07:29.520|DEBUG|QuickSearch#SearchPlugin:Failed request to ITAD
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
26-05 15:07:29.520|DEBUG|QuickSearch#SearchPlugin:Failed request to ITAD
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
```
I was wondering why I wasn't getting any results at all, and found this.

**Comment by felixkmh** [comment]
This shouldn't prevent any other results from being displayed though. You can try to disable ITAD search in the options. This will also cause the index to be renewed, potentially fixing your problem.

**Comment by Jeshibu** [comment]
Sorry, forgot to reply - you were right. Index being busted is its own problem then.
