### ISSUE TITLE
[Bug] Failed to load plugin settings

### ISSUE THREAD

**Issue by BloodShed-Oni** [felixkmh/QuickSearch-for-Playnite#57]
When trying to open the settings for the plugin I get "Failed to load plugin settings"

Here's the log entry from playnite.log

> 27-06 14:49:00.345|ERROR|PluginSettingsHelper:Failed to load plugin settings, 6a604592-7001-4b4e-a3be-91073b459e2b
> Newtonsoft.Json.JsonSerializationException: Error setting value to 'EnableGlobalHotkey' on 'QuickSearch.SearchSettings'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at QuickSearch.SearchPlugin.RegisterGlobalHotkey() in E:\Programmierung\playnite-dev\QuickSearch\source\SearchPlugin.cs:line 147
>    at QuickSearch.SearchSettings.set_EnableGlobalHotkey(Boolean value) in E:\Programmierung\playnite-dev\QuickSearch\source\Settings\SearchSettings.cs:line 139
>    at SetEnableGlobalHotkey(Object , Object )
>    at Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target, Object value)
>    --- End of inner exception stack trace ---
>    at Newtonsoft.Json.Serialization.DynamicValueProvider.SetValue(Object target, Object value)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at QuickSearch.SearchSettings.BeginEdit() in E:\Programmierung\playnite-dev\QuickSearch\source\Settings\SearchSettings.cs:line 248
>    at Playnite.DesktopApp.ViewModels.PluginSettingsHelper.GetPluginSettingsView(Guid pluginId, ExtensionFactory extensions, Dictionary`2 loadedPluginSettings) in C:\projects\playnite\source\Playnite.DesktopApp\PluginSettingsHelper.cs:line 48
> 27-06 14:49:02.726|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.AddonsWindowFactory, False.

**Comment by felixkmh** [comment]
fixed in v2.24.1
