### ISSUE TITLE
[Bug] Diacritics not fully ignored

### ISSUE THREAD

**Issue by xunkar** [felixkmh/QuickSearch-for-Playnite#66]
As of now, a game named "Astérix" can be found by typing "Asterix", however not all diacritics currently support this behavior. Please add support for basic substitution of the macron (ā, ī, ū, ē, ō as a, i, u, e, o).

**Comment by felixkmh** [comment]
Done via 9c5f989a63f46e06f17b74cb4709947f7f3a34aa
